--1
SELECT CNO, CNAME
FROM COURSES
WHERE STUDYEAR = 1
ORDER BY CNAME

--2
SELECT COUNT (*)
FROM STUDENTS
WHERE SNAME LIKE 'A%'

--3
SELECT CITY, COUNT (*)
FROM STUDENTS
GROUP BY CITY

--4
SELECT DISTINCT TEACHERS.TNO, TITLE, TNAME, COURSES.CNO, CNAME
FROM TEACHERS
	JOIN TSC ON TSC.TNO = TEACHERS.TNO
	JOIN COURSES ON COURSES.CNO = TSC.CNO

--5
SELECT DISTINCT TEACHERS.TNO
FROM TEACHERS
WHERE TNO NOT IN 
(
SELECT TNO
FROM TSC, COURSES
WHERE TSC.CNO=COURSES.CNO AND STUDYEAR = 1
)

--6
SELECT TOP 1 STUDYEAR
FROM COURSES
GROUP BY STUDYEAR
ORDER BY COUNT(*) DESC

--7
SELECT TOP 1 STUDYEAR
FROM COURSES
	JOIN TSC ON TSC.CNO = COURSES.CNO
GROUP BY STUDYEAR
ORDER BY AVG(GRADE) DESC

--8
SELECT COUNT (*)
FROM TEACHERS
WHERE TNO NOT IN
(
SELECT TNO
FROM TSC
)

--9
SELECT STUDYEAR, SUM(HOURS)
FROM COURSES
	JOIN TSC ON TSC.CNO = COURSES.CNO
GROUP BY STUDYEAR
ORDER BY STUDYEAR

--10
SELECT TOP 1 STUDENTS.SNO, SNAME
FROM STUDENTS, TSC
WHERE TSC.SNO = STUDENTS.SNO
GROUP BY STUDENTS.SNO, SNAME
ORDER BY AVG(GRADE) DESC

--11
SELECT STUDENTS.SNO, SNAME
FROM STUDENTS, TSC
WHERE TSC.SNO = STUDENTS.SNO
GROUP BY STUDENTS.SNO, SNAME
ORDER BY AVG(GRADE) DESC

--12
SELECT TNO, TITLE, TNAME
FROM TEACHERS
WHERE TNO IN
(
SELECT TOP 1 SUPNO
FROM TEACHERS
GROUP BY SUPNO
HAVING COUNT(*) = (
		SELECT TOP 1 COUNT(*)
		FROM TEACHERS
		GROUP BY SUPNO 
		ORDER BY COUNT(*) DESC
	)
)

--13
SELECT TNO, TITLE, TNAME
FROM TEACHERS
WHERE SUPNO IS NULL

--14
SELECT TEACHERS.TNO, TNAME, COUNT(*)
FROM TEACHERS
	JOIN TSC ON TSC.TNO = TEACHERS.TNO
GROUP BY TEACHERS.TNO, TNAME
HAVING COUNT(*) > 3

--15
SELECT DISTINCT STUDENTS.SNO, SNAME
FROM STUDENTS
	JOIN TSC ON TSC.SNO = STUDENTS.SNO
WHERE GRADE = 5.0

--16
SELECT DISTINCT STUDENTS.SNO, SNAME
FROM STUDENTS
	JOIN TSC ON TSC.SNO = STUDENTS.SNO
WHERE GRADE = (
				SELECT MAX(GRADE)
				FROM TSC
			)

--17
SELECT COUNT(DISTINCT SNO)
FROM TSC
WHERE CNO = 'C2'

--18
CREATE VIEW NAZWA AS
SELECT TSC.TNO, TITLE, TNAME, TSC.SNO, SNAME, TSC.CNO, CNAME, TSC.HOURS, GRADE
FROM TSC
	JOIN STUDENTS ON STUDENTS.SNO = TSC.SNO
	JOIN TEACHERS ON TEACHERS.TNO = TSC.TNO
	JOIN COURSES ON COURSES.CNO = TSC.CNO

--19
SELECT CITY, COUNT(*) 
FROM
(
	SELECT CITY
	FROM TEACHERS
	UNION ALL
	SELECT CITY
	FROM STUDENTS
) TAB
GROUP BY CITY


--20
SELECT TNO, TITLE, TNAME
FROM TEACHERS
WHERE TNO IN (
	SELECT TOP 1 TNO
	FROM TSC
	GROUP BY TNO
	ORDER BY AVG(GRADE)
)

--21
CREATE TABLE ARCHIVE (
	TNO VARCHAR(2) NOT NULL,
	TNAME VARCHAR(40) NOT NULL,
	SNO VARCHAR(2) NOT NULL,
	SNAME VARCHAR(40) NOT NULL,
	CNO VARCHAR(2) NOT NULL,
	CNAME VARCHAR(40) NOT NULL,
	HOURS INT NOT NULL,
	GRADE FLOAT NOT NULL
	PRIMARY KEY(TNO,SNO,CNO)
)

INSERT INTO ARCHIVE 
SELECT TSC.TNO, TNAME, TSC.SNO, SNAME, TSC.CNO, CNAME, TSC.HOURS, GRADE
FROM TSC
	JOIN STUDENTS ON STUDENTS.SNO = TSC.SNO
	JOIN TEACHERS ON TEACHERS.TNO = TSC.TNO
	JOIN COURSES ON COURSES.CNO = TSC.CNO

DROP TABLE ARCHIVE

SELECT * FROM ARCHIVE

--22
CREATE VIEW ZAD22 AS
SELECT CNAME, AVG(GRADE) AS AVGRADE
FROM TSC, COURSES
WHERE TSC.CNO = COURSES.CNO
GROUP BY CNAME

SELECT CNAME, AVGRADE
FROM ZAD22
WHERE AVGRADE > (SELECT AVG(AVGRADE) FROM ZAD22)

DROP VIEW ZAD22

--23

SELECT TEACHERS.TNO, TITLE, TNAME
FROM STUDENTS, TSC, COURSES, TEACHERS
WHERE STUDENTS.SNO = TSC.SNO AND COURSES.CNO = TSC.CNO AND STUDYEAR = 1 AND TEACHERS.TNO = TSC.TNO AND STUDENTS.CITY = TEACHERS.CITY

--24
SELECT CNO, CNAME
FROM COURSES
WHERE CNO IN
(
SELECT TOP 1 CNO
FROM TSC
GROUP BY CNO
ORDER BY  COUNT (DISTINCT SNO) 
)

--25
SELECT SYEAR, AVG(GRADE)
FROM STUDENTS, TSC
WHERE TSC.SNO = STUDENTS.SNO
GROUP BY SYEAR
ORDER BY AVG(GRADE) DESC

select SYEAR, AVG(GRADE)
from STUDENTS, TSC
where STUDENTS.SNO = TSC.SNO
group by SYEAR
order by 2 desc